name: build
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build:
    if: "(!contains(github.event.head_commit.message, 'skip build') && !contains(github.event.head_commit.message, 'build skip'))"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        id: validate_gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 1.8
        id: setup_jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make Gradle Wrapper Executable
        id: make_executable
        run: chmod +x ./gradlew

      - name: Build for Artifacts
        id: build
        run: ./gradlew jar shadowJar

      - name: Upload Generated Files as Artifact
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: "JDABotHelper"
          path: build/libs/

      - name: Prepare MavenCentral publishing
        id: prepare_publish
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        run: bash -c "echo '${GPG_KEY_CONTENTS}' | base64 -d > '${SIGNING_SECRET_KEY_RING_FILE}'"

      - name: Publish to MavenCentral
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseRepository