name: build
on: [ pull_request, push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        id: validate_gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 1.8
        id: setup_jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make Gradle Wrapper Executable
        id: make_executable
        run: chmod +x ./gradlew

      - name: Build
        id: build
        run: ./gradlew jar shadowJar

      - name: Upload Generated Files
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: "JDABotHelper"
          path: build/libs/

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: publish
        run: ./gradlew publish
